- lib/templates/v_0.4.0/api/api-routes.js
- lib/templates/v_0.4.0/api/server-controllers.js
- lib/templates/v_0.4.0/client/scaffold-factory.js
- lib/templates/v_0.4.0/client/ui-controllers.js
- lib/templates/v_0.4.0/client/ui-factory.js
update a bunch of stuff in the cli. main things are:
pagination for posts
update controllers/templates for latest yote
> Updates 3 15

- lib/reactResource.js
- lib/scaffold.js
- lib/templates/v_0.6.0/client/components/Create.js.jsx
- lib/templates/v_0.6.0/client/components/Form.js.jsx
- lib/templates/v_0.6.0/client/components/Update.js.jsx
- lib/templates/v_0.6.0/client/reducers/singleReducers.js
- package.json
fixed component names not lining up (single and listitem were switched)
fixed annoying indents on form components
added "defaultItem" at top of reducers. makes it easier to add fields to the react forms.
> fixes for generated components

- lib/templates/v_0.6.0/client/components/Create.js.jsx
- lib/templates/v_0.6.0/client/components/Update.js.jsx
this uses lodash to look at the input names that are passed in to update newState.  
Example would be a model that looks like this: 
``` 
showing: {
title: "",
listing: { 
address: "",
city: "",
}
}
``` 
with this you can pass in the target in dot notation like so:
```
...
<TextInput 
name="title"
.... 
/>
<TextInput
name="listing.address"
...
/>
....
```
> bring in _handleChangeForm method that works with nested objects

- lib/templates/v_0.6.0/client/actions/listActions.js
- lib/templates/v_0.6.0/client/actions/singleActions.js
- lib/templates/v_0.6.0/client/components/Create.js.jsx
- lib/templates/v_0.6.0/client/components/List.js.jsx
- lib/templates/v_0.6.0/client/components/Update.js.jsx
- lib/templates/v_0.6.0/client/reducers/listReducers.js
- lib/templates/v_0.6.0/client/reducers/singleReducers.js
- package.json
write the CLI templates to use fetchListIfNeeded and other actions associated with it to optimize list performance for large data sets.
> List performance

- lib/v_0.7.0/add.js
- lib/v_0.7.0/clientResource.js
- lib/v_0.7.0/init.js
- lib/v_0.7.0/serverResource.js
- lib/v_0.7.0/templates/client/actions.js
- lib/v_0.7.0/templates/client/components/Create.js.jsx
- lib/v_0.7.0/templates/client/components/Form.js.jsx
- lib/v_0.7.0/templates/client/components/Layout.js.jsx
- lib/v_0.7.0/templates/client/components/List.js.jsx
- lib/v_0.7.0/templates/client/components/ListItem.js.jsx
- lib/v_0.7.0/templates/client/components/Single.js.jsx
- lib/v_0.7.0/templates/client/components/Update.js.jsx
- lib/v_0.7.0/templates/client/reducers.js
- lib/v_0.7.0/templates/client/routes.js.jsx
- lib/v_0.7.0/templates/client/styles.scss
- lib/v_0.7.0/templates/server/Model.js
- lib/v_0.7.0/templates/server/api.js
- lib/v_0.7.0/templates/server/controller.js
- package.json
- tools/utils.js
- yote-cli.js
made the yote-cli templates match the proper style guides from Yote product resource. 
added some color and helper logs to the CLI to make it a little more readable.  
Added ability initialize Yote Mobile with `$ yote init <myNewApp> -i` (was pretty easy)
> NOTE:  Have not done anything with mobile resources.  that stuff still needs a lot of work.   @austincline09 maybe? :)
> Style match

- lib/v_0.7.0/clientResource.js
- lib/v_0.7.0/init.js
- lib/v_0.7.0/serverResource.js
- lib/v_0.7.0/templates/client/actions.js
- lib/v_0.7.0/templates/client/components/Create.js.jsx
- lib/v_0.7.0/templates/client/components/Form.js.jsx
- lib/v_0.7.0/templates/client/components/Layout.js.jsx
- lib/v_0.7.0/templates/client/components/List.js.jsx
- lib/v_0.7.0/templates/client/components/ListItem.js.jsx
- lib/v_0.7.0/templates/client/components/Single.js.jsx
- lib/v_0.7.0/templates/client/components/Update.js.jsx
- lib/v_0.7.0/templates/client/reducers.js
- lib/v_0.7.0/templates/client/routes.js.jsx
- lib/v_0.7.0/templates/client/styles.scss
- lib/v_0.7.0/templates/server/Model.js
- lib/v_0.7.0/templates/server/api.js
- lib/v_0.7.0/templates/server/controller.js
- package.json
Changed `__Proper__` to `__PascalName__` in all the templates. 
Added correct `__PascalName__` references for mobile `init`
> Fix PascalNames 

- lib/v_0.7.0/serverResource.js
- lib/v_0.7.0/templates/client/components/Form.js.jsx
- lib/v_0.7.0/templates/client/components/Update.js.jsx
- package.json
fix Update template
change "var" to "let" in server db
> remove card from form

- lib/v_0.7.0/templates/client/actions.js
- package.json
these guys werent actually catching for null and would throw errors if it was undefined
> Null results

- lib/v_0.7.0/templates/client/actions.js
- package.json
fix shouldFetch functionality. 2 changes:
for list, being length == 0 is valid and should not result in a new fetch. this can result in an infinite loop.
for single, check "isFetching" before checking if its in the map. can also result in an infinite loop.
> fix should fetch

- lib/v_0.7.0/templates/client/actions.js
- lib/v_0.7.0/templates/client/reducers.js
- package.json
for notes see pull request in yote
https://github.com/fugitivelabs/yote/pull/53/files
> should fetch updates

- lib/v_0.7.0/add.js
- lib/v_0.7.0/init.js
- lib/v_0.7.0/mobileResource.js
- lib/v_0.7.0/templates/mobile/actions.js
- lib/v_0.7.0/templates/mobile/components/Create.js
- lib/v_0.7.0/templates/mobile/components/Layout.js
- lib/v_0.7.0/templates/mobile/components/List.js
- lib/v_0.7.0/templates/mobile/components/ListItem.js
- lib/v_0.7.0/templates/mobile/components/Single.js
- lib/v_0.7.0/templates/mobile/components/Update.js
- lib/v_0.7.0/templates/mobile/reducers.js
- lib/v_0.7.0/templates/mobile/styles.js
- package.json
- tools/utils.js
**NOTE**: must add route to ./mobile/XXX/js/global/components/tabs/TabsView.ios.js or ./mobile/XXX/js/global/components/tabs/TabsView.android.js & ./mobile/XXX/js/MainNavigator.js or ./mobile/XXX/js/LoggedOutNavigator.js to get access to file
> Add Mobile Resource

- lib/v_0.7.0/templates/client/components/Create.js.jsx
- lib/v_0.7.0/templates/client/components/Form.js.jsx
- lib/v_0.7.0/templates/client/components/Update.js.jsx
- lib/v_0.7.0/templates/server/Model.js
- package.json
make it easier to follow style guide with CLI generated components
> Model defaults

- README.md
- lib/v_0.7.0/templates/client/actions.js
- lib/v_0.7.0/templates/client/reducers.js
- lib/v_0.7.0/templates/server/api.js
- lib/v_0.7.0/templates/server/controller.js
- package.json
- tools/remote.js
also updates backup utils and README
> latest yote util methods

- README.md
- lib/v_0.7.0/templates/client/actions.js
- lib/v_0.7.0/templates/client/components/Create.js.jsx
- lib/v_0.7.0/templates/client/components/Update.js.jsx
- lib/v_0.7.0/templates/client/reducers.js
- lib/v_0.7.0/templates/server/api.js
- lib/v_0.7.0/templates/server/controller.js
- package.json
- tools/remote.js
merge after #51. fix weird state thing that mazen noticed on the form update function and fix multi line comment.
> Fix state update

- lib/v_0.7.0/templates/client/reducers.js
- package.json
see Yote #80 
https://github.com/fugitivelabs/yote/pull/80
published to npm
> fix for single.getItem()

- lib/v_0.7.0/init.js
- lib/v_0.7.0/mobileResource.js
- lib/v_0.7.0/templates/client/actions.js
- lib/v_0.7.0/templates/client/reducers.js
- lib/v_0.7.0/templates/mobile/actions.js
- lib/v_0.7.0/templates/mobile/components/Create.js
- lib/v_0.7.0/templates/mobile/components/Layout.js
- lib/v_0.7.0/templates/mobile/components/List.js
- lib/v_0.7.0/templates/mobile/components/ListItem.js
- lib/v_0.7.0/templates/mobile/components/Single.js
- lib/v_0.7.0/templates/mobile/components/Update.js
- lib/v_0.7.0/templates/mobile/navigator.js
- lib/v_0.7.0/templates/mobile/reducers.js
- lib/v_0.7.0/templates/mobile/styles.js
- package.json
- yote-cli.js
- mobile navigation
- updated mobile components
- updated actions/reducers for client and mobile
- added kebabName to mobile actions
> Austin branch

- lib/v_0.7.0/templates/client/components/Create.js.jsx
- lib/v_0.7.0/templates/client/components/Update.js.jsx
- lib/v_0.7.0/templates/mobile/components/Create.js
- lib/v_0.7.0/templates/mobile/components/Update.js
- package.json
also make mobile us the "defaultItem" values from the reducer
> Remove JSON.parse from Create and Update forms

- lib/v_0.7.0/templates/client/reducers.js
- package.json
see https://github.com/fugitivelabs/yote/pull/92
published
> Reducer util checks

- lib/v_0.7.0/init.js
- package.json
make v0.7.0 clone the yote branch v0.7-release
> v0.7 into master

- lib/v_0.8.0/templates/mobile/components/List.js
- lib/v_0.8.0/templates/mobile/components/ListItem.js
- lib/v_0.8.0/templates/mobile/styles.js
- lib/v_0.8.0/templates/mobile/views/Create.js
- lib/v_0.8.0/templates/mobile/views/Root.js
- lib/v_0.8.0/templates/mobile/views/Single.js
- condense react native imports from 'react-native'
- removed reference to that icon
> v0.8-release - condense react-native imports

- lib/v_0.8.0/templates/client/views/List.js.jsx
- package.json
change template list.map to list `key={thing._id + i}`
> Fix list key

- lib/v_0.8.0/templates/server/api.js
- lib/v_0.8.0/templates/server/controller.js
- package.json
>  new server action actions to allow more general querying

- lib/v_0.8.0/templates/client/actions.js
- lib/v_0.8.0/templates/mobile/actions.js
- package.json
https://github.com/fugitivelabs/yote/pull/118
> fetch list updates re: yote #118

- lib/v_0.8.0/templates/client/views/Create.js.jsx
- lib/v_0.8.0/templates/mobile/views/Create.js
- package.json
see yote #119 https://github.com/fugitivelabs/yote/pull/119
> use deep copy in templates instead of spread

- lib/v_0.8.0/templates/client/views/Single.js.jsx
- lib/v_0.8.0/templates/client/views/Update.js.jsx
- package.json
This popped up all over in redstone and romr.  
should check whether the selected item is fetching, not the store itself
> fix the __thingStore__.isFetching to __thingStore__.selected.isFetching

- lib/v_0.8.0/templates/client/actions.js
- lib/v_0.8.0/templates/client/reducers.js
- lib/v_0.8.0/templates/mobile/actions.js
- lib/v_0.8.0/templates/mobile/reducers.js
- package.json
> set selected action and reducer

- lib/v_0.9.0/templates/server/api.js
- lib/v_0.9.0/templates/server/controller.js
- lib/v_0.9.0/templates/web/actions.js
- lib/v_0.9.0/templates/web/reducers.js
- lib/v_0.9.0/templates/web/views/Create.js.jsx
looks like 0.9 is already merged into master here, so even though this is called 0.9 its really just master
update the cli templates with latest yote
> 0.9 - template updates

- lib/v_0.9.0/templates/web/reducers.js
- lib/v_0.9.0/templates/web/views/List.js.jsx
- Add getListInfo to the reducer.
- Update List view to use getListInfo.
> master - 0.9 reducer getListInfo

- lib/v_0.9.0/templates/web/admin/views/AdminCreate.js.jsx
- lib/v_0.9.0/templates/web/admin/views/AdminList.js.jsx
- lib/v_0.9.0/templates/web/admin/views/AdminUpdate.js.jsx
- lib/v_0.9.0/templates/web/views/Create.js.jsx
- lib/v_0.9.0/templates/web/views/Update.js.jsx
- Update handleFormChange methods. We were directly mutating state and then setting infinitely nested newState on every update.
- Use getListInfo on AdminList.
> master - form change bug

- lib/v_0.8.0/init.js
- lib/v_0.9.0/addMobileResource.js
- lib/v_0.9.0/init.js
- lib/v_0.9.0/templates/mobile/Navigator.js
- lib/v_0.9.0/templates/mobile/actions.js
- lib/v_0.9.0/templates/mobile/components/Layout.js
- lib/v_0.9.0/templates/mobile/components/List.js
- lib/v_0.9.0/templates/mobile/components/ListItem.js
- lib/v_0.9.0/templates/mobile/reducers.js
- lib/v_0.9.0/templates/mobile/styles.js
- lib/v_0.9.0/templates/mobile/views/Create.js
- lib/v_0.9.0/templates/mobile/views/Root.js
- lib/v_0.9.0/templates/mobile/views/Single.js
- lib/v_0.9.0/templates/mobile/views/Update.js
- lib/v_0.9.0/templates/web/views/Create.js.jsx
- package-lock.json
- tools/run.js
- super old mobile changes that were never merged? 
- react native update version
- resource Layout file instead of Root to match web
- mobile yarn install
> master - V0.9.1 mobile

- tools/run.js
- fixed yote run options to work as expected
- added "tabs" option to run all in current tabs instead of separate windows
> master - Run all in same terminal window

- lib/v_0.9.0/init.js
- package-lock.json
- package.json
same thing with yote, even more so here. need to get back to a proper baseline.
> master - 0.9
